### ISSUE TITLE
Ajout du layout

### ISSUE THREAD

**Issue by blazarecki** [CloudIntra/cloudintra-webapp#8]
- [x] Ajout du layout global
- [x] Ajout du squelette de menu
- [x] Ajout du bouton d'action (en bas à droite)

**Comment by ChristopheBoucaut** [comment]
Reste juste à reformuler les phrases des TU pour essayer de faire plus explicites et voir si je sors des éléments du layout dans des fichiers à part ou si je laisse tout dans le index.html (je pense laisser dedans, car si non on aura un effet "vide", le temps que les morceaux soient chargés). (cc @blazarecki )

**Comment by ChristopheBoucaut** [comment]
fix by #19
